version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - VIRTUAL_HOST=${MINIO_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${MINIO_VIRTUAL_HOST}
      - VIRTUAL_PORT=9000
    volumes:
      - ./data/minio/data:/data:z
      - ./data/minio/certs:/root/.minio/certs:z
    command: minio server /data --console-address ":9001"

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf:/etc/nginx/conf.d
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/dhparam:/etc/nginx/dhparam
      - ./nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL
      - ACME_CA_URI
    volumes:
      - ./nginx-proxy/conf:/etc/nginx/conf.d
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/dhparam:/etc/nginx/dhparam
      - ./nginx-proxy/certs:/etc/nginx/certs:rw
      - ./nginx-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
