version: "3.9"

services:
  strapi:
    image: varsafar/strapi-stateless
    restart: always
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=2048
      - DATABASE_CLIENT
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=1337
    networks:
      - root_default

networks:
  root_default:
    external: true
