version: "3.8"

services:
  strapi:
    image: strapi/strapi:alpine
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=1337
      - NODE_OPTIONS=--max_old_space_size=2048
    volumes:
      - ./app:/srv/app
    command: strapi build && strapi start
    networks:
      - root_default

networks:
  root_default:
    external: true
