version: "3.9"

services:
  outline:
    image: outlinewiki/outline
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=3000
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - root_default

networks:
  root_default:
    external: true
